spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create
    show-sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/botica
    username: postgres
    password: example

jwt:
  auth:
    app: Spring-Security-app
    secret_key: botica#secret@123
    expires_in: 3600